CREATE DATABASE TRAVEL_BLISS;

USE TRAVEL_BLISS;
CREATE TABLE INFO(name VARCHAR(40),email VARCHAR(25),phone_no VARCHAR(15),
gender VARCHAR(15),travel_date DATE,destination VARCHAR(30), add_notes TEXT);
